package promovolve.api.projection

import org.apache.pekko.Done
import org.apache.pekko.actor.typed.ActorSystem
import org.apache.pekko.stream.QueueOfferResult
import org.apache.pekko.stream.scaladsl.{ Keep, Sink, Source }
import slick.jdbc.PostgresProfile.api.*
import java.time.Instant
import scala.concurrent.{ ExecutionContext, Future }
import scala.concurrent.duration.*
import promovolve.api.TrackEvent

/**
 * Tracking event for persistence in the journal table.
 *
 * This is the persistent form of impression/click events that the
 * Pekko Projection will read to build dashboard aggregates.
 */
case class TrackingEvent(
    sequenceNr: Long,
    eventType: String, // "impression" | "click" | "cta_click" | "fold" | "unfold"
    eventTime: Instant,
    siteId: String,
    campaignId: Option[String],
    advertiserId: Option[String],
    creativeId: String,
    category: Option[String],
    cpm: Option[BigDecimal],
    url: Option[String],
    slot: Option[String],
    requestId: Option[String], // UUID (batch path) or 16-char hex hash (fold tokens)
    dogeared: Boolean = false // True for impressions served because of an honored pin
)

/**
 * Writes tracking events to append-only journal for projection.
 *
 * Uses Pekko Streams for reliable batched writes with backpressure.
 * Events are buffered and flushed in batches (max 100 events or 100ms)
 * to minimize database round-trips while ensuring low latency.
 */
class TrackingEventJournal(db: slick.jdbc.JdbcBackend#Database)(
    using
    ec: ExecutionContext,
    system: ActorSystem[?]
) {

  import TrackingEventJournal.*

  private val log = org.slf4j.LoggerFactory.getLogger(getClass)

  // Bounded queue with backpressure - drops newest events if overwhelmed
  private val (queue, done) = Source
    .queue[TrackingEvent](10000)
    .groupedWithin(100, 100.millis) // Batch: max 100 events or 100ms
    .mapAsync(4) { batch => // 4 parallel DB writes
      db.run(trackingEvents ++= batch)
        .map { _ =>
          log.debug("Wrote batch of {} tracking events", batch.size)
        }
        .recover { case ex =>
          log.warn("Failed to write batch of {} events: {}", batch.size, ex.getMessage)
        }
    }
    .toMat(Sink.ignore)(Keep.both)
    .run()

  /** Write impression event to journal (non-blocking) */
  def writeImpression(e: TrackEvent): Unit = {
    val event = TrackingEvent(
      sequenceNr = 0L, // Auto-generated by database
      eventType = "impression",
      eventTime = Instant.ofEpochMilli(e.ts),
      siteId = e.pub,
      campaignId = e.campaignId,
      advertiserId = e.advertiserId,
      creativeId = e.cid,
      category = e.category,
      cpm = e.cpm.map(BigDecimal(_)),
      url = Some(e.url),
      slot = Some(e.slot),
      requestId = e.requestId,
      dogeared = e.dogeared
    )

    queue.offer(event) match {
      case QueueOfferResult.Dropped =>
        log.warn("Tracking event dropped due to buffer overflow")
      case QueueOfferResult.Failure(ex) =>
        log.warn("Failed to queue tracking event: {}", ex.getMessage)
      case _ => // Enqueued or QueueClosed - ok
    }
  }

  /** Write click event to journal (non-blocking) */
  def writeClick(e: TrackEvent): Unit = {
    val event = TrackingEvent(
      sequenceNr = 0L,
      eventType = "click",
      eventTime = Instant.ofEpochMilli(e.ts),
      siteId = e.pub,
      campaignId = e.campaignId,
      advertiserId = e.advertiserId,
      creativeId = e.cid,
      category = e.category,
      cpm = None, // Clicks don't have CPM
      url = Some(e.url),
      slot = Some(e.slot),
      requestId = e.requestId,
      dogeared = e.dogeared
    )

    queue.offer(event) match {
      case QueueOfferResult.Dropped =>
        log.warn("Tracking event dropped due to buffer overflow")
      case QueueOfferResult.Failure(ex) =>
        log.warn("Failed to queue tracking event: {}", ex.getMessage)
      case _ => // Enqueued or QueueClosed - ok
    }
  }

  /**
   * Write fold event to journal. Folds are free (engagement signal,
   * not billed) — no per-event price column. Non-blocking.
   */
  def writeFold(e: TrackEvent): Unit = {
    val event = TrackingEvent(
      sequenceNr = 0L,
      eventType = "fold",
      eventTime = Instant.ofEpochMilli(e.ts),
      siteId = e.pub,
      campaignId = e.campaignId,
      advertiserId = e.advertiserId,
      creativeId = e.cid,
      category = e.category,
      cpm = None,
      url = Some(e.url),
      slot = Some(e.slot),
      requestId = e.requestId
    )

    queue.offer(event) match {
      case QueueOfferResult.Dropped =>
        log.warn("Tracking event dropped due to buffer overflow")
      case QueueOfferResult.Failure(ex) =>
        log.warn("Failed to queue tracking event: {}", ex.getMessage)
      case _ =>
    }
  }

  /** Write unfold event to journal. Telemetry only — no billing impact. */
  def writeUnfold(e: TrackEvent): Unit = {
    val event = TrackingEvent(
      sequenceNr = 0L,
      eventType = "unfold",
      eventTime = Instant.ofEpochMilli(e.ts),
      siteId = e.pub,
      campaignId = e.campaignId,
      advertiserId = e.advertiserId,
      creativeId = e.cid,
      category = e.category,
      cpm = None,
      url = Some(e.url),
      slot = Some(e.slot),
      requestId = e.requestId
    )

    queue.offer(event) match {
      case QueueOfferResult.Dropped =>
        log.warn("Tracking event dropped due to buffer overflow")
      case QueueOfferResult.Failure(ex) =>
        log.warn("Failed to queue tracking event: {}", ex.getMessage)
      case _ =>
    }
  }

  def writeCTAClick(e: TrackEvent): Unit = {
    val event = TrackingEvent(
      sequenceNr = 0L,
      eventType = "cta_click",
      eventTime = Instant.ofEpochMilli(e.ts),
      siteId = e.pub,
      campaignId = e.campaignId,
      advertiserId = e.advertiserId,
      creativeId = e.cid,
      category = e.category,
      cpm = None,
      url = Some(e.url),
      slot = Some(e.slot),
      requestId = e.requestId,
      dogeared = e.dogeared
    )

    queue.offer(event) match {
      case QueueOfferResult.Dropped =>
        log.warn("Tracking event dropped due to buffer overflow")
      case QueueOfferResult.Failure(ex) =>
        log.warn("Failed to queue tracking event: {}", ex.getMessage)
      case _ =>
    }
  }

  /**
   * Gracefully shutdown, draining any buffered events.
   * Call this on application shutdown to avoid losing events.
   */
  def shutdown(): Future[Done] = {
    queue.complete()
    done
  }

  /** Read events from offset (for custom source provider if needed) */
  def readFromOffset(fromSequenceNr: Long, limit: Int): Future[Seq[TrackingEvent]] =
    db.run(
      trackingEvents
        .filter(_.sequenceNr > fromSequenceNr)
        .sortBy(_.sequenceNr)
        .take(limit)
        .result
    )

  /**
   * Aggregate impressions by (creativeId, url, slot) for the given
   * creatives on a site over the lookback window. Powers the Serving
   * tab's "delivered to" placement list — the ServeIndex is slot-keyed
   * with no URL, so historical impressions are the only source of
   * (url, slot, count) attribution per serving creative.
   */
  def listServingPlacements(
      siteId: String,
      creativeIds: Set[String],
      since: Instant
  ): Future[Vector[ServingPlacementRow]] = {
    if (creativeIds.isEmpty) Future.successful(Vector.empty)
    else db.run(
      trackingEvents
        .filter(e =>
          e.siteId === siteId
          && e.eventType === "impression"
          && (e.creativeId.inSet(creativeIds))
          && e.eventTime >= since
          && e.url.isDefined
          && e.slot.isDefined
        )
        .groupBy(e => (e.creativeId, e.url, e.slot, e.category))
        .map { case ((cid, url, slot, cat), rows) =>
          (cid, url, slot, cat, rows.length)
        }
        .result
    ).map(_.iterator.map { case (cid, url, slot, cat, n) =>
      ServingPlacementRow(cid, url.getOrElse(""), slot.getOrElse(""), cat, n.toLong)
    }.toVector)
  }
}

/**
 * Aggregate row used by `listServingPlacements`: a (creative, url,
 * slot) triple with its impression count over the lookback window.
 */
case class ServingPlacementRow(
    creativeId: String,
    url: String,
    slot: String,
    category: Option[String],
    impressions: Long
)

object TrackingEventJournal {

  import promovolve.SlickMappers.given

  // Slick table definition
  class TrackingEventsTable(tag: Tag) extends Table[TrackingEvent](tag, "tracking_events") {
    def sequenceNr = column[Long]("sequence_nr", O.AutoInc)
    def eventType = column[String]("event_type")
    def eventTime = column[Instant]("event_time")
    def siteId = column[String]("site_id")
    def campaignId = column[Option[String]]("campaign_id")
    def advertiserId = column[Option[String]]("advertiser_id")
    def creativeId = column[String]("creative_id")
    def category = column[Option[String]]("category")
    def cpm = column[Option[BigDecimal]]("cpm")
    def url = column[Option[String]]("url")
    def slot = column[Option[String]]("slot")
    def requestId = column[Option[String]]("request_id") // UUID or hashed token
    def dogeared = column[Boolean]("dogeared") // Impression served via honored pin

    def * = (
      sequenceNr,
      eventType,
      eventTime,
      siteId,
      campaignId,
      advertiserId,
      creativeId,
      category,
      cpm,
      url,
      slot,
      requestId,
      dogeared
    ).mapTo[TrackingEvent]
  }

  val trackingEvents = TableQuery[TrackingEventsTable]

  // Insert query that returns the generated sequence number
  val trackingEventsInsert = trackingEvents.returning(trackingEvents.map(_.sequenceNr))
}
