apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promovolve
resources:
  - seccomp-installer.yaml
configMapGenerator:
  - name: chromium-seccomp
    files:
      - chromium.json=../../docker/chromium-seccomp.json
