package promovolve.taxonomy

import org.slf4j.LoggerFactory

import scala.io.Source
import scala.util.Using

/**
 * Lookup table mapping legacy IAB Content Taxonomy 2.x numeric IDs to their
 * IAB Content Taxonomy 3.0 equivalent.
 *
 * Loaded from `/iab_content_taxonomy/legacy_2x_to_3_0.tsv` at startup. The
 * TSV is generated by `scripts/generate_legacy_iab_mapping.py` and committed
 * alongside the source taxonomies so the migration is reviewable and
 * reproducible — there is no official IAB 2.x → 3.0 mapping.
 *
 * Use this when reading persisted state (event replay, snapshot recovery,
 * stored config) that may still contain 2.x IDs. New code should write
 * 3.0 IDs directly.
 */
object Iab2xTo3xMigration {

  private val logger = LoggerFactory.getLogger(getClass)
  private val ResourcePath = "/iab_content_taxonomy/legacy_2x_to_3_0.tsv"

  /** Outcome of resolving a legacy ID. */
  sealed trait Resolution
  object Resolution {

    /** Legacy id mapped to a 3.0 id. */
    case class Mapped(v30Id: String, matchType: String) extends Resolution

    /**
     * Legacy id was a descriptive-vector (Channel/Type/Media/etc.) that 3.0
     * removed from topical content. Callers should drop the id.
     */
    case object Dropped extends Resolution

    /**
     * Legacy id is not in the table — could be already-migrated 3.0,
     * or unknown. Callers should pass it through unchanged.
     */
    case object Unknown extends Resolution
  }

  private case class Entry(v30Id: String, matchType: String)

  private lazy val table: Map[String, Entry] = load()

  private def load(): Map[String, Entry] = {
    Option(getClass.getResourceAsStream(ResourcePath)) match {
      case None =>
        logger.warn(s"Iab2xTo3xMigration: lookup resource missing at $ResourcePath")
        Map.empty
      case Some(is) =>
        Using.resource(Source.fromInputStream(is, "UTF-8")) { src =>
          src.getLines()
            .filterNot(l => l.startsWith("#") || l.startsWith("legacy_id\t") || l.trim.isEmpty)
            .flatMap { line =>
              line.split("\t", -1) match {
                case Array(legacy, v30, _, mtype, _*) if legacy.nonEmpty =>
                  Some(legacy -> Entry(v30, mtype))
                case _ => None
              }
            }
            .toMap
        }
    }
  }

  /**
   * Look up a legacy id. Returns `Unknown` for ids not in the table — the
   * caller should pass those through unchanged (likely already 3.0).
   */
  def resolve(legacyId: String): Resolution =
    table.get(legacyId) match {
      case None                       => Resolution.Unknown
      case Some(e) if e.v30Id.isEmpty => Resolution.Dropped
      case Some(e)                    => Resolution.Mapped(e.v30Id, e.matchType)
    }

  /**
   * Translate a legacy id to its 3.0 equivalent.
   *
   *   - `Mapped(v30, _)` → `Some(v30)`
   *   - `Dropped`        → `None` (caller should drop the id)
   *   - `Unknown`        → `Some(legacyId)` (pass-through; assumed already 3.0)
   */
  def toV30(legacyId: String): Option[String] =
    resolve(legacyId) match {
      case Resolution.Mapped(v30, _) => Some(v30)
      case Resolution.Dropped        => None
      case Resolution.Unknown        => Some(legacyId)
    }

  /** Bulk-migrate a set of ids, silently dropping descriptive-vector entries. */
  def migrateSet(ids: Set[String]): Set[String] =
    ids.flatMap(toV30)

  /** Number of legacy ids known to the table (including dropped). */
  def size: Int = table.size

  /** Whether the lookup table was loaded successfully. */
  def isLoaded: Boolean = table.nonEmpty
}
