package promovolve.taxonomy

import scala.annotation.tailrec
import scala.io.Source
import scala.util.Using

/** What level of the hierarchy a [[Place]] sits at. */
enum PlaceKind:
  case Country, Subdivision, City

/**
 * One node of the geographic vocabulary.
 *
 * `parent` is the code of the enclosing place, never derived by parsing
 * `code`. City codes are opaque GeoNames ids precisely so nobody is
 * tempted to infer structure from the string.
 */
final case class Place(
    code: String,
    name: String, // English, canonical — feeds prompts and matching
    kind: PlaceKind,
    parent: Option[String],
    population: Long = 0L
)

/**
 * The closed geographic vocabulary: countries (ISO 3166-1 alpha-2),
 * first-level subdivisions (ISO 3166-2), and cities (GeoNames ids,
 * prefixed `GN`).
 *
 * Closed is the point. Every geographic value that enters the system —
 * an LLM's answer about what a page is about, a publisher's audience
 * declaration, an advertiser's targeting set — is checked against this
 * table and dropped if absent, so downstream matching is plain set
 * intersection over a vocabulary both sides share. See
 * `docs/design/GEOGRAPHIC_CONTEXT.md`.
 *
 * Tables are generated by `scripts/build-places.sh`; codes come from ISO
 * and cities from GeoNames. The two disagree about subdivision numbering
 * (GeoNames JP.13 is Hyogo, ISO JP-13 is Tokyo), which is why the build
 * links cities to ISO subdivisions by name and leaves `parent` at the
 * country when it cannot match confidently — a coarser answer, never a
 * wrong one.
 */
object Places {

  private val CountriesPath = "/places/countries"
  private val SubdivisionsPath = "/places/subdivisions"
  private val CitiesPath = "/places/cities"

  private lazy val byCode: Map[String, Place] = {
    val countries = loadTsv(s"$CountriesPath.tsv", 2) { cols =>
      Place(cols(0), cols(1), PlaceKind.Country, None)
    }
    val subdivisions = loadTsv(s"$SubdivisionsPath.tsv", 3) { cols =>
      Place(cols(0), cols(2), PlaceKind.Subdivision, Some(cols(1)))
    }
    val cities = loadTsv(s"$CitiesPath.tsv", 5) { cols =>
      // admin1 may be blank when the build could not map GeoNames'
      // admin1 onto an ISO subdivision; the city then hangs off its
      // country directly.
      val parent = if (cols(3).nonEmpty) cols(3) else cols(2)
      Place(cols(0), cols(1), PlaceKind.City, Some(parent), cols(4).toLongOption.getOrElse(0L))
    }
    (countries ++ subdivisions ++ cities).map(p => p.code -> p).toMap
  }

  /** Localized display names per compiled-in language, keyed by place code. */
  private lazy val localized: Map[String, Map[String, String]] = {
    val perFile = List(CountriesPath, SubdivisionsPath, CitiesPath).map(LocalizedNames.loadAll)
    LocalizedNames.langs.map { lang =>
      lang -> perFile.foldLeft(Map.empty[String, String])((acc, m) => acc ++ m.getOrElse(lang, Map.empty))
    }.toMap
  }

  /** Search index: normalized name → codes, built once from both languages. */
  private lazy val searchIndex: Vector[(String, Place)] = {
    val locales = localized.values.flatten.toVector
    val fromLocal = locales.flatMap { case (code, name) => byCode.get(code).map(p => normalize(name) -> p) }
    val fromEn = byCode.valuesIterator.map(p => normalize(p.name) -> p).toVector
    (fromEn ++ fromLocal).distinct
  }

  def get(code: String): Option[Place] = byCode.get(code)

  def contains(code: String): Boolean = byCode.contains(code)

  /** Keep only codes this vocabulary knows. The validation gate. */
  def validate(codes: Iterable[String]): Set[String] = codes.filter(contains).toSet

  def size: Int = byCode.size

  /**
   * Enclosing places, nearest first: `GN1860672` → `[JP-14, JP]`.
   * Excludes the place itself. Cycle-guarded — a malformed table must
   * degrade, not hang.
   */
  def ancestors(code: String): List[Place] = {
    @tailrec
    def loop(current: Option[String], seen: Set[String], acc: List[Place]): List[Place] =
      current.flatMap(byCode.get) match {
        case Some(p) if !seen.contains(p.code) => loop(p.parent, seen + p.code, p :: acc)
        case _                                 => acc.reverse
      }
    byCode.get(code).map(p => loop(p.parent, Set(code), Nil)).getOrElse(Nil)
  }

  /**
   * Expand places to (themselves ∪ their ancestors), keeping the MINIMUM
   * hop distance for each: 0 = named directly, 1 = parent, 2 =
   * grandparent. Mirrors `AuctioneerEntity.expandWithHops` so the two
   * vocabularies decay relevance the same way.
   *
   * Unknown codes contribute nothing — validation is not this method's
   * job, but it must not invent nodes either.
   */
  def expandWithHops(codes: Iterable[String]): Map[String, Int] =
    codes.iterator
      .filter(contains)
      .flatMap(c => (c, 0) +: ancestors(c).zipWithIndex.map { case (p, i) => (p.code, i + 1) })
      .toVector
      .groupMapReduce(_._1)(_._2)(math.min)

  /**
   * Does a campaign's targeting set match a piece of inventory?
   *
   * The inventory side is expanded to ancestors, the targeting side is
   * not. That asymmetry IS the rule: targeting `{JP}` matches a site
   * declaring Kamakura (JP is one of its ancestors), while targeting
   * `{JP-13}` does NOT match inventory that only says `JP` — no
   * descendant match, matching how category targeting already behaves.
   * An advertiser who wants both writes `{JP-13, JP}`.
   *
   * Two boundary cases, both load-bearing:
   *   - empty targeting matches everything (the contextual default,
   *     same as an empty `siteAllowlist`)
   *   - non-empty targeting does NOT match empty inventory. Undeclared
   *     is UNKNOWN, not "everywhere" — see the tier-2 section of
   *     docs/design/GEOGRAPHIC_CONTEXT.md. This falls out of the
   *     expansion rather than needing its own branch, but it is the
   *     rule most likely to be "fixed" by mistake.
   */
  def targetingMatches(targeting: Set[String], inventory: Set[String]): Boolean =
    targeting.isEmpty || expandWithHops(inventory).keysIterator.exists(targeting.contains)

  /**
   * How far a targeting set sits from a piece of inventory, or None when it
   * does not match at all.
   *
   * `Some(0)` means the inventory names a targeted place directly;
   * `Some(1)` its parent; and so on. Untargeted is `Some(0)` — no
   * constraint is a perfect fit, not a distant one, or every untargeted
   * campaign would be quietly penalised.
   *
   * The distinction from [[targetingMatches]] is what the caller does with
   * it: audience targeting is a binary gate, while CONTENT place targeting
   * is relevance, and relevance decays with distance. A campaign targeting
   * Japan on an article about Kamakura is a worse fit than one targeting
   * Kamakura, and should lose to it.
   */
  def matchHops(targeting: Set[String], inventory: Set[String]): Option[Int] =
    if (targeting.isEmpty) Some(0)
    else {
      val expanded = expandWithHops(inventory)
      targeting.iterator.flatMap(expanded.get).minOption
    }

  /** Localized display name for `code` in `lang`, if translated. */
  def nameIn(lang: String, code: String): Option[String] =
    localized.get(LocalizedNames.primary(lang)).flatMap(_.get(code))

  /** Localized name when we have one, else the canonical English name, else the code. */
  def displayName(lang: String, code: String): String =
    nameIn(lang, code).orElse(byCode.get(code).map(_.name)).getOrElse(code)

  /**
   * Type-ahead over English and localized names, for the publisher's
   * audience declaration and the advertiser's targeting picker — both
   * sides pick from the same vocabulary so neither has to type a code.
   *
   * Prefix matches rank above substring matches; within a rank, larger
   * places first (population for cities, and countries/subdivisions
   * ahead of cities since their population is 0 but they are broader).
   */
  def search(query: String, limit: Int = 20): List[Place] = {
    val q = normalize(query)
    if (q.isEmpty) Nil
    else {
      val kindRank = (p: Place) =>
        p.kind match {
          case PlaceKind.Country     => 0
          case PlaceKind.Subdivision => 1
          case PlaceKind.City        => 2
        }
      searchIndex.iterator
        .collect { case (name, p) if name.startsWith(q) => (0, p) }
        .++(searchIndex.iterator.collect { case (name, p) if !name.startsWith(q) && name.contains(q) => (1, p) })
        .toVector
        .distinctBy { case (rank, p) => (rank, p.code) }
        .sortBy { case (rank, p) => (rank, kindRank(p), -p.population, p.name) }
        .map(_._2)
        .distinctBy(_.code)
        .take(limit)
        .toList
    }
  }

  /** Diacritic- and punctuation-insensitive key, matching the build script. */
  private def normalize(s: String): String =
    java.text.Normalizer
      .normalize(s, java.text.Normalizer.Form.NFD)
      .toLowerCase
      // NFD splits diacritics into combining marks, which are not
      // letters or digits — so this one filter drops accents and
      // punctuation together.
      .filter(_.isLetterOrDigit)

  private def loadTsv(resourcePath: String, minCols: Int)(build: Array[String] => Place): Vector[Place] =
    Option(getClass.getResourceAsStream(resourcePath)) match {
      case None =>
        // A missing table is a packaging fault, not a runtime condition —
        // every geographic value would silently fail validation.
        throw new IllegalStateException(s"Place table missing from the classpath: $resourcePath")
      case Some(is) =>
        Using(Source.fromInputStream(is, "UTF-8")) { source =>
          source
            .getLines()
            .drop(1) // header
            .filter(_.nonEmpty)
            .map(_.split("\t", -1))
            .filter(_.length >= minCols)
            .map(build)
            .toVector
        }.get
    }
}
